services:
  - type: web
    name: video-editing-portfolio
    plan: free
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn prtf.asgi:application -k uvicorn.workers.UvicornWorker'
    runtime: python                             